# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrowserWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Browser(object):
    def setupUi(self, Browser):
        Browser.setObjectName("Browser")
        Browser.resize(886, 762)
        self.gridLayout = QtWidgets.QGridLayout(Browser)
        self.gridLayout.setObjectName("gridLayout")
        self.ToolButton_refresh = ToolButton(Browser)
        self.ToolButton_refresh.setObjectName("ToolButton_refresh")
        self.gridLayout.addWidget(self.ToolButton_refresh, 0, 2, 1, 1)
        self.ToolButton_forward = ToolButton(Browser)
        self.ToolButton_forward.setObjectName("ToolButton_forward")
        self.gridLayout.addWidget(self.ToolButton_forward, 0, 1, 1, 1)
        self.SearchLineEdit = SearchLineEdit(Browser)
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.gridLayout.addWidget(self.SearchLineEdit, 0, 3, 1, 1)
        self.ToolButton_back = ToolButton(Browser)
        self.ToolButton_back.setObjectName("ToolButton_back")
        self.gridLayout.addWidget(self.ToolButton_back, 0, 0, 1, 1)
        self.ToggleToolButton_pin = ToggleToolButton(Browser)
        self.ToggleToolButton_pin.setObjectName("ToggleToolButton_pin")
        self.gridLayout.addWidget(self.ToggleToolButton_pin, 0, 4, 1, 1)

        self.retranslateUi(Browser)
        QtCore.QMetaObject.connectSlotsByName(Browser)

    def retranslateUi(self, Browser):
        _translate = QtCore.QCoreApplication.translate
        Browser.setWindowTitle(_translate("Browser", "Frame"))
from qfluentwidgets import SearchLineEdit, ToggleToolButton, ToolButton
