# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_video_window(object):
    def setupUi(self, video_window):
        video_window.setObjectName("video_window")
        video_window.resize(750, 566)
        self.gridLayout = QtWidgets.QGridLayout(video_window)
        self.gridLayout.setObjectName("gridLayout")
        self.PrimaryToolButton_play = PrimaryToolButton(video_window)
        self.PrimaryToolButton_play.setObjectName("PrimaryToolButton_play")
        self.gridLayout.addWidget(self.PrimaryToolButton_play, 0, 0, 1, 1)

        self.retranslateUi(video_window)
        QtCore.QMetaObject.connectSlotsByName(video_window)

    def retranslateUi(self, video_window):
        _translate = QtCore.QCoreApplication.translate
        video_window.setWindowTitle(_translate("video_window", "Frame"))
from qfluentwidgets import PrimaryToolButton
